name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --release

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release

      - name: Verify binary
        run: ./target/release/snap --version
